Traceback (most recent call last):
  File "/scratch/zs1542/CV-FinalProject/CVFramework/prune.py", line 163, in <module>
    torch.save(model.state_dict(), model_file)
  File "/scratch/zs1542/envs/py38/lib/python3.9/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/scratch/zs1542/envs/py38/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/scratch/zs1542/envs/py38/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/zs1542/CV-FinalProject/CVFramework/checkpoints/encoder_10.pth'
